phoenix:
  enable: true
  url: jdbc:phoenix:10.40.152.9,10.40.152.13,10.40.152.5:2181
  type: com.alibaba.druid.pool.DruidDataSource
  driver-class-name: org.apache.phoenix.jdbc.PhoenixDriver
  default-auto-commit: true
  maxActive: 20
  maxWait: 60000
  minIdle: 5
  timeBetweenEvictionRunsMillis: 60000
  minEvictableIdleTimeMillis: 60000
  poolPreparedStatements: true
  maxPoolPreparedStatementPerConnectionSize: 20
  testWhileIdle: true
  testOnBorrow: false
  testOnReturn: false
  initialSize: 1
  validationQuery: SELECT 1 + 1 FROM RVM_BIGDATA_ENV
  username:
  password:

server:
  connection-timeout: 60000
  port: 8081
  address:

#FROM RVM_BIGDATA_ENV
#  url: jdbc:phoenix:10.40.150.17,10.40.150.27,10.40.150.2,10.40.150.10:2181

rvm_bigdata:
  signals_statistics: select * from RVM_BIGDATA_ENV where "vin"={0} and "tboxTime">={1} and "tboxTime"<={2} order by "{3}" {4} limit {5} offset {6}
  signals_count: select count(*) from RVM_BIGDATA_ENV where "vin"={0} and "tboxTime">={1} and "tboxTime"<={2}

  multipleSignals_statistics: select * from RVM_BIGDATA_ENV where "vin"={0} and "tboxTime">={1} and "tboxTime"<={2} order by "{3}" {4} limit {5} offset {6}
  multipleSignals_count: select count(*) from RVM_BIGDATA_ENV where "vin"={0} and "tboxTime">={1} and "tboxTime"<={2}

alter_code:
  alter_statistics: select "alert_code",count(distinct "vin") as "num" from RVM_ALERT_RECORD_DIST where "alert_start_time">={0} and "alert_start_time"<={1} group by "alert_code" limit {2} offset {3}
  alter_car_num: select count(distinct "vin") from RVM_ALERT_RECORD_DIST where "alert_start_time">={0} and "alert_start_time"<={1}
  offline_num: select count("vin") from TB_ACCOUNT_OFFLINE_BOUND_STATUS_MID;
  alter_total_num: select count(*) from RVM_ALERT_RECORD_DIST where "alert_start_time">={0} and "alert_start_time"<={1}

last_report:
  last_statistics: select "vin","platform","latest_report_time","latitude","longitude" from RVM_LATEST_UPLOAD_LOCATION where latest_report_time<={0} order by "{1}" {2} limit {3} offset {4}
  last_num: select count(*) from RVM_LATEST_UPLOAD_LOCATION where "latest_report_time"<={0}