phoenix:
  enable: true
  url: jdbc:phoenix:10.40.150.17:2181
  type: com.alibaba.druid.pool.DruidDataSource
  driver-class-name: org.apache.phoenix.jdbc.PhoenixDriver
  default-auto-commit: true
  maxActive: 100
  initialSize: 0
  validationQuery: select 1 + 1 from RVM_BIGDATA_ENV
  username:
  password:


server:
  port: 8080
  address:

#  url: jdbc:phoenix:10.40.150.17:2181